"""account notifications, draft form version, waitlist

Revision ID: 80a4f5b2b084
Revises: 3926882b8c03
Create Date: 2026-08-14 15:33:33.846810

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "80a4f5b2b084"
down_revision: str | None = "3926882b8c03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "waitlist_entry",
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("program_id", "email"),
    )
    op.create_index(
        op.f("ix_waitlist_entry_program_id"),
        "waitlist_entry",
        ["program_id"],
        unique=False,
    )
    op.add_column(
        "account",
        sa.Column(
            "notify_new_message",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.add_column(
        "account",
        sa.Column(
            "notify_match_published",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.add_column(
        "account",
        sa.Column(
            "notify_milestone_reminders",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.add_column(
        "account",
        sa.Column(
            "notify_broadcasts",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.add_column(
        "account",
        sa.Column(
            "digest_frequency",
            sa.String(length=16),
            server_default="weekly",
            nullable=False,
        ),
    )
    op.add_column(
        "application_draft", sa.Column("form_version_id", sa.UUID(), nullable=True)
    )
    # Named, because an unnamed constraint cannot be dropped again — the
    # autogenerated downgrade passes None and fails at the first rollback.
    op.create_foreign_key(
        "fk_application_draft_form_version_id",
        "application_draft",
        "form_version",
        ["form_version_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_application_draft_form_version_id",
        "application_draft",
        type_="foreignkey",
    )
    op.drop_column("application_draft", "form_version_id")
    op.drop_column("account", "digest_frequency")
    op.drop_column("account", "notify_broadcasts")
    op.drop_column("account", "notify_milestone_reminders")
    op.drop_column("account", "notify_match_published")
    op.drop_column("account", "notify_new_message")
    op.drop_index(op.f("ix_waitlist_entry_program_id"), table_name="waitlist_entry")
    op.drop_table("waitlist_entry")
    # ### end Alembic commands ###
