"""core schema

Revision ID: 1f71404e4ef4
Revises:
Create Date: 2026-08-14 09:31:07.601517

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "1f71404e4ef4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("photo_url", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "magic_link_token",
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(
        op.f("ix_magic_link_token_email"), "magic_link_token", ["email"], unique=False
    )
    op.create_table(
        "organisation",
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "audit_event",
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_name", sa.String(length=200), nullable=False),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("subject_label", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_event_action"), "audit_event", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_event_actor_name"), "audit_event", ["actor_name"], unique=False
    )
    op.create_index(op.f("ix_audit_event_at"), "audit_event", ["at"], unique=False)
    op.create_index(
        op.f("ix_audit_event_organisation_id"),
        "audit_event",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "notification_preference",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("new_message", sa.Boolean(), nullable=False),
        sa.Column("match_published", sa.Boolean(), nullable=False),
        sa.Column("milestone_reminders", sa.Boolean(), nullable=False),
        sa.Column("broadcasts", sa.Boolean(), nullable=False),
        sa.Column("digest", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id"),
    )
    op.create_table(
        "program",
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("cohort_start", sa.Date(), nullable=True),
        sa.Column("cohort_end", sa.Date(), nullable=True),
        sa.Column("applications_close_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("matching_opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_commitment", sa.Text(), nullable=True),
        sa.Column("eligibility", sa.Text(), nullable=True),
        sa.Column("open_roles", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("recruitment_goal", sa.Integer(), nullable=True),
        sa.Column("self_matching_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "slug"),
    )
    op.create_index(
        op.f("ix_program_organisation_id"), "program", ["organisation_id"], unique=False
    )
    op.create_table(
        "session_token",
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(
        op.f("ix_session_token_account_id"),
        "session_token",
        ["account_id"],
        unique=False,
    )
    op.create_table(
        "application_draft",
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_draft_email"), "application_draft", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_application_draft_program_id"),
        "application_draft",
        ["program_id"],
        unique=False,
    )
    op.create_table(
        "broadcast",
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("segment", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("recipient_count", sa.Integer(), nullable=False),
        sa.Column("delivered_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_broadcast_program_id"), "broadcast", ["program_id"], unique=False
    )
    op.create_table(
        "form_version",
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("program_id", "role", "version"),
    )
    op.create_index(
        op.f("ix_form_version_program_id"), "form_version", ["program_id"], unique=False
    )
    op.create_table(
        "invite",
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("invited_by_name", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(op.f("ix_invite_email"), "invite", ["email"], unique=False)
    op.create_index(
        op.f("ix_invite_program_id"), "invite", ["program_id"], unique=False
    )
    op.create_table(
        "matching_recipe",
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "hard_constraints", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("weights", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fairness", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_by", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_matching_recipe_program_id"),
        "matching_recipe",
        ["program_id"],
        unique=False,
    )
    op.create_table(
        "message_template",
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("updated_by", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("program_id", "kind"),
    )
    op.create_index(
        op.f("ix_message_template_program_id"),
        "message_template",
        ["program_id"],
        unique=False,
    )
    op.create_table(
        "participation",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("is_coordinator", sa.Boolean(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("load", sa.Integer(), nullable=True),
        sa.Column("profile_completeness", sa.Float(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("headline", sa.Text(), nullable=True),
        sa.Column("skills", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("matched", sa.Boolean(), nullable=False),
        sa.Column("muted", sa.Boolean(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "program_id"),
    )
    op.create_index(
        op.f("ix_participation_account_id"),
        "participation",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_participation_program_id"),
        "participation",
        ["program_id"],
        unique=False,
    )
    op.create_table(
        "program_milestone",
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("week_offset", sa.Integer(), nullable=False),
        sa.Column("strand_prompt", sa.Text(), nullable=True),
        sa.Column("reminder_days_before", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_program_milestone_program_id"),
        "program_milestone",
        ["program_id"],
        unique=False,
    )
    op.create_table(
        "resource",
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resource_program_id"), "resource", ["program_id"], unique=False
    )
    op.create_table(
        "run",
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("recipe_version", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_by", sa.String(length=200), nullable=True),
        sa.Column("drafted_count", sa.Integer(), nullable=False),
        sa.Column("published_count", sa.Integer(), nullable=False),
        sa.Column("coverage_rate", sa.Float(), nullable=True),
        sa.Column(
            "fairness_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_run_program_id"), "run", ["program_id"], unique=False)
    op.create_table(
        "strand",
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("origin_mode", sa.String(length=16), nullable=False),
        sa.Column("match_rationale", sa.Text(), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_session_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sessions_logged", sa.Integer(), nullable=False),
        sa.Column("milestones_completed", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_strand_program_id"), "strand", ["program_id"], unique=False
    )
    op.create_table(
        "application",
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("form_version_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(length=200), nullable=True),
        sa.Column("editable_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("matching_opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["form_version_id"],
            ["form_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_email"), "application", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_application_program_id"), "application", ["program_id"], unique=False
    )
    op.create_index(
        op.f("ix_application_status"), "application", ["status"], unique=False
    )
    op.create_table(
        "application_resume_token",
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("draft_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["application_draft.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "draft_pair",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("mentee_participation_id", sa.UUID(), nullable=False),
        sa.Column("mentor_participation_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("priority_band", sa.String(length=16), nullable=False),
        sa.Column(
            "score_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mentee_participation_id"],
            ["participation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mentor_participation_id"],
            ["participation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_draft_pair_run_id"), "draft_pair", ["run_id"], unique=False
    )
    op.create_table(
        "message",
        sa.Column("strand_id", sa.UUID(), nullable=False),
        sa.Column("author_participation_id", sa.UUID(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivery_state", sa.String(length=16), nullable=False),
        sa.Column("client_token", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_participation_id"],
            ["participation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strand_id"],
            ["strand.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_sent_at"), "message", ["sent_at"], unique=False)
    op.create_index(
        op.f("ix_message_strand_id"), "message", ["strand_id"], unique=False
    )
    op.create_table(
        "run_unmatched",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("participation_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["participation_id"],
            ["participation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_run_unmatched_run_id"), "run_unmatched", ["run_id"], unique=False
    )
    op.create_table(
        "strand_member",
        sa.Column("strand_id", sa.UUID(), nullable=False),
        sa.Column("participation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["participation_id"],
            ["participation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strand_id"],
            ["strand.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("strand_id", "participation_id"),
    )
    op.create_index(
        op.f("ix_strand_member_participation_id"),
        "strand_member",
        ["participation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_strand_member_strand_id"), "strand_member", ["strand_id"], unique=False
    )
    op.create_table(
        "message_read",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("participation_id", sa.UUID(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["participation_id"],
            ["participation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id", "participation_id"),
    )
    op.create_index(
        op.f("ix_message_read_message_id"), "message_read", ["message_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_read_message_id"), table_name="message_read")
    op.drop_table("message_read")
    op.drop_index(op.f("ix_strand_member_strand_id"), table_name="strand_member")
    op.drop_index(op.f("ix_strand_member_participation_id"), table_name="strand_member")
    op.drop_table("strand_member")
    op.drop_index(op.f("ix_run_unmatched_run_id"), table_name="run_unmatched")
    op.drop_table("run_unmatched")
    op.drop_index(op.f("ix_message_strand_id"), table_name="message")
    op.drop_index(op.f("ix_message_sent_at"), table_name="message")
    op.drop_table("message")
    op.drop_index(op.f("ix_draft_pair_run_id"), table_name="draft_pair")
    op.drop_table("draft_pair")
    op.drop_table("application_resume_token")
    op.drop_index(op.f("ix_application_status"), table_name="application")
    op.drop_index(op.f("ix_application_program_id"), table_name="application")
    op.drop_index(op.f("ix_application_email"), table_name="application")
    op.drop_table("application")
    op.drop_index(op.f("ix_strand_program_id"), table_name="strand")
    op.drop_table("strand")
    op.drop_index(op.f("ix_run_program_id"), table_name="run")
    op.drop_table("run")
    op.drop_index(op.f("ix_resource_program_id"), table_name="resource")
    op.drop_table("resource")
    op.drop_index(
        op.f("ix_program_milestone_program_id"), table_name="program_milestone"
    )
    op.drop_table("program_milestone")
    op.drop_index(op.f("ix_participation_program_id"), table_name="participation")
    op.drop_index(op.f("ix_participation_account_id"), table_name="participation")
    op.drop_table("participation")
    op.drop_index(op.f("ix_message_template_program_id"), table_name="message_template")
    op.drop_table("message_template")
    op.drop_index(op.f("ix_matching_recipe_program_id"), table_name="matching_recipe")
    op.drop_table("matching_recipe")
    op.drop_index(op.f("ix_invite_program_id"), table_name="invite")
    op.drop_index(op.f("ix_invite_email"), table_name="invite")
    op.drop_table("invite")
    op.drop_index(op.f("ix_form_version_program_id"), table_name="form_version")
    op.drop_table("form_version")
    op.drop_index(op.f("ix_broadcast_program_id"), table_name="broadcast")
    op.drop_table("broadcast")
    op.drop_index(
        op.f("ix_application_draft_program_id"), table_name="application_draft"
    )
    op.drop_index(op.f("ix_application_draft_email"), table_name="application_draft")
    op.drop_table("application_draft")
    op.drop_index(op.f("ix_session_token_account_id"), table_name="session_token")
    op.drop_table("session_token")
    op.drop_index(op.f("ix_program_organisation_id"), table_name="program")
    op.drop_table("program")
    op.drop_table("notification_preference")
    op.drop_index(op.f("ix_audit_event_organisation_id"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_at"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_actor_name"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_action"), table_name="audit_event")
    op.drop_table("audit_event")
    op.drop_table("organisation")
    op.drop_index(op.f("ix_magic_link_token_email"), table_name="magic_link_token")
    op.drop_table("magic_link_token")
    op.drop_table("account")
    # ### end Alembic commands ###
