"""rate limit counter

Revision ID: 2d879bfa7a79
Revises: 80a4f5b2b084
Create Date: 2026-08-15 18:58:28.133160

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "2d879bfa7a79"
down_revision: str | None = "80a4f5b2b084"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limit_counter",
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("key", "window_start"),
    )
    # ### end Alembic commands ###

    # The sweep in app.limits deletes by window alone, which without this is the
    # one query in the module that scans the whole table.
    op.create_index(
        "ix_rate_limit_counter_window_start",
        "rate_limit_counter",
        ["window_start"],
    )


def downgrade() -> None:
    op.drop_index("ix_rate_limit_counter_window_start", "rate_limit_counter")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rate_limit_counter")
    # ### end Alembic commands ###
