"""participant attribute projection

Revision ID: 3926882b8c03
Revises: 1f71404e4ef4
Create Date: 2026-08-14 11:10:47.690622

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "3926882b8c03"
down_revision: str | None = "1f71404e4ef4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "participant_attribute",
        sa.Column("participation_id", sa.UUID(), nullable=False),
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("field_id", sa.UUID(), nullable=False),
        sa.Column("matching", sa.Boolean(), nullable=False),
        sa.Column("equity", sa.Boolean(), nullable=False),
        sa.Column("field_type", sa.String(length=32), nullable=False),
        sa.Column("text_value", sa.Text(), nullable=True),
        sa.Column("number_value", sa.Float(), nullable=True),
        sa.Column("option_values", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["participation_id"],
            ["participation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("participation_id", "field_id"),
    )
    op.create_index(
        op.f("ix_participant_attribute_participation_id"),
        "participant_attribute",
        ["participation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_participant_attribute_program_id"),
        "participant_attribute",
        ["program_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_participant_attribute_program_id"), table_name="participant_attribute"
    )
    op.drop_index(
        op.f("ix_participant_attribute_participation_id"),
        table_name="participant_attribute",
    )
    op.drop_table("participant_attribute")
    # ### end Alembic commands ###
